version: '3'
services:
  jenkins:
    # image: jenkins/jenkins:2.235.4
    build: .
    user: root
    container_name: jenkins_s
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
